[versions]
agp = "8.1.4"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
firebaseBom = "32.7.0"
playServicesAuth = "20.7.0"
viewpager2 = "1.0.0"
cardview = "1.0.0"
itextpdf = "5.5.13.2"
mlkitFaceDetection = "16.1.7"
cameraXVersion = "1.3.0"
cameraXViewVersion = "1.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
itextpdf = { group = "com.itextpdf", name = "itextpdf", version.ref = "itextpdf" }
mlkit-face-detection = { group = "com.google.mlkit", name = "face-detection", version.ref = "mlkitFaceDetection" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraXVersion" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraXVersion" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraXVersion" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraXViewVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
